# Generated by Django 5.2.1 on 2025-05-11 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours_useful', models.PositiveIntegerField(verbose_name='Полезно (часов)')),
                ('hours_doubtful', models.PositiveIntegerField(verbose_name='Сомнительно (часов)')),
                ('hours_wasted', models.PositiveIntegerField(verbose_name='В никуда (часов)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
